"""initial SQLAlchemy schema

Revision ID: 45d50651d793
Revises: 
Create Date: 2026-08-27 19:46:24.071405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45d50651d793'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('passwordHash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('PATIENT', 'DONOR', 'HOSPITAL', 'BLOOD_BANK', 'ADMIN', name='Role'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'PENDING', 'SUSPENDED', name='UserStatus'), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_User_email'), 'User', ['email'], unique=True)
    op.create_index(op.f('ix_User_role'), 'User', ['role'], unique=False)
    op.create_index(op.f('ix_User_status'), 'User', ['status'], unique=False)
    op.create_table('AuditLog',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('userId', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity', sa.String(length=100), nullable=True),
    sa.Column('entityId', sa.String(length=36), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['User.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_AuditLog_userId'), 'AuditLog', ['userId'], unique=False)
    op.create_table('BloodBank',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('userId', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('registrationNumber', sa.String(length=100), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['User.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('registrationNumber'),
    sa.UniqueConstraint('userId')
    )
    op.create_table('Donor',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('userId', sa.String(length=36), nullable=False),
    sa.Column('bloodGroup', sa.Enum('A_POS', 'A_NEG', 'B_POS', 'B_NEG', 'AB_POS', 'AB_NEG', 'O_POS', 'O_NEG', name='BloodGroup'), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('availabilityStatus', sa.Boolean(), nullable=False),
    sa.Column('lastDonationDate', sa.DateTime(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['User.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('userId')
    )
    op.create_table('Hospital',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('userId', sa.String(length=36), nullable=False),
    sa.Column('hospitalName', sa.String(length=200), nullable=False),
    sa.Column('registrationNumber', sa.String(length=100), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['User.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('registrationNumber'),
    sa.UniqueConstraint('userId')
    )
    op.create_table('Notification',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('userId', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('isRead', sa.Boolean(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['User.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('Notification_userId_isRead_idx', 'Notification', ['userId', 'isRead'], unique=False)
    op.create_index(op.f('ix_Notification_userId'), 'Notification', ['userId'], unique=False)
    op.create_table('Patient',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('userId', sa.String(length=36), nullable=False),
    sa.Column('bloodGroup', sa.Enum('A_POS', 'A_NEG', 'B_POS', 'B_NEG', 'AB_POS', 'AB_NEG', 'O_POS', 'O_NEG', name='BloodGroup'), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['User.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('userId')
    )
    op.create_table('BloodInventory',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('bloodBankId', sa.String(length=36), nullable=False),
    sa.Column('bloodGroup', sa.Enum('A_POS', 'A_NEG', 'B_POS', 'B_NEG', 'AB_POS', 'AB_NEG', 'O_POS', 'O_NEG', name='BloodGroup'), nullable=False),
    sa.Column('unitsAvailable', sa.Integer(), nullable=False),
    sa.Column('unitsReserved', sa.Integer(), nullable=False),
    sa.Column('expiryDate', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bloodBankId'], ['BloodBank.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_BloodInventory_bloodBankId'), 'BloodInventory', ['bloodBankId'], unique=False)
    op.create_table('BloodRequest',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patientId', sa.String(length=36), nullable=True),
    sa.Column('hospitalId', sa.String(length=36), nullable=True),
    sa.Column('bloodGroup', sa.Enum('A_POS', 'A_NEG', 'B_POS', 'B_NEG', 'AB_POS', 'AB_NEG', 'O_POS', 'O_NEG', name='BloodGroup'), nullable=False),
    sa.Column('unitsRequired', sa.Integer(), nullable=False),
    sa.Column('urgency', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'PROCESSING', 'FULFILLED', 'REJECTED', 'CANCELLED', name='RequestStatus'), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['hospitalId'], ['Hospital.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patientId'], ['Patient.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Donation',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('donorId', sa.String(length=36), nullable=False),
    sa.Column('bloodBankId', sa.String(length=36), nullable=True),
    sa.Column('hospitalId', sa.String(length=36), nullable=True),
    sa.Column('bloodGroup', sa.Enum('A_POS', 'A_NEG', 'B_POS', 'B_NEG', 'AB_POS', 'AB_NEG', 'O_POS', 'O_NEG', name='BloodGroup'), nullable=False),
    sa.Column('units', sa.Integer(), nullable=False),
    sa.Column('donationDate', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bloodBankId'], ['BloodBank.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['donorId'], ['Donor.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['hospitalId'], ['Hospital.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('EmergencyRequest',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('requesterId', sa.String(length=36), nullable=False),
    sa.Column('hospitalId', sa.String(length=36), nullable=True),
    sa.Column('bloodGroup', sa.Enum('A_POS', 'A_NEG', 'B_POS', 'B_NEG', 'AB_POS', 'AB_NEG', 'O_POS', 'O_NEG', name='BloodGroup'), nullable=False),
    sa.Column('unitsRequired', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('urgency', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'MATCHED', 'FULFILLED', 'CANCELLED', 'EXPIRED', name='EmergencyStatus'), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['hospitalId'], ['Hospital.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requesterId'], ['Patient.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_EmergencyRequest_requesterId'), 'EmergencyRequest', ['requesterId'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_EmergencyRequest_requesterId'), table_name='EmergencyRequest')
    op.drop_table('EmergencyRequest')
    op.drop_table('Donation')
    op.drop_table('BloodRequest')
    op.drop_index(op.f('ix_BloodInventory_bloodBankId'), table_name='BloodInventory')
    op.drop_table('BloodInventory')
    op.drop_table('Patient')
    op.drop_index(op.f('ix_Notification_userId'), table_name='Notification')
    op.drop_index('Notification_userId_isRead_idx', table_name='Notification')
    op.drop_table('Notification')
    op.drop_table('Hospital')
    op.drop_table('Donor')
    op.drop_table('BloodBank')
    op.drop_index(op.f('ix_AuditLog_userId'), table_name='AuditLog')
    op.drop_table('AuditLog')
    op.drop_index(op.f('ix_User_status'), table_name='User')
    op.drop_index(op.f('ix_User_role'), table_name='User')
    op.drop_index(op.f('ix_User_email'), table_name='User')
    op.drop_table('User')
    # ### end Alembic commands ###
