"""init

Revision ID: e8da54798817
Revises: 
Create Date: 2026-08-18 09:27:47.943731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e8da54798817'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_prisma_migrations')
    op.alter_column('AuditLog', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('AuditLog', 'userId',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               existing_nullable=True)
    op.alter_column('AuditLog', 'action',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('AuditLog', 'entity',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               nullable=True)
    op.alter_column('AuditLog', 'entityId',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               existing_nullable=True)
    op.alter_column('AuditLog', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('AuditLog', 'createdAt',
               existing_type=postgresql.TIMESTAMP(precision=3),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index('AuditLog_action_createdAt_idx', table_name='AuditLog')
    op.create_index(op.f('ix_AuditLog_userId'), 'AuditLog', ['userId'], unique=False)
    op.drop_constraint('AuditLog_userId_fkey', 'AuditLog', type_='foreignkey')
    op.create_foreign_key(None, 'AuditLog', 'User', ['userId'], ['id'], ondelete='SET NULL')
    op.alter_column('BloodBank', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('BloodBank', 'userId',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('BloodBank', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               existing_nullable=False)
    op.alter_column('BloodBank', 'registrationNumber',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('BloodBank', 'city',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('BloodBank', 'address',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.drop_index('BloodBank_registrationNumber_key', table_name='BloodBank')
    op.drop_index('BloodBank_userId_key', table_name='BloodBank')
    op.create_unique_constraint(None, 'BloodBank', ['registrationNumber'])
    op.create_unique_constraint(None, 'BloodBank', ['userId'])
    op.alter_column('BloodInventory', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('BloodInventory', 'bloodBankId',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('BloodInventory', 'updatedAt',
               existing_type=postgresql.TIMESTAMP(precision=3),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.drop_index('BloodInventory_bloodBankId_bloodGroup_idx', table_name='BloodInventory')
    op.create_index(op.f('ix_BloodInventory_bloodBankId'), 'BloodInventory', ['bloodBankId'], unique=False)
    op.drop_constraint('BloodInventory_bloodBankId_fkey', 'BloodInventory', type_='foreignkey')
    op.create_foreign_key(None, 'BloodInventory', 'BloodBank', ['bloodBankId'], ['id'], ondelete='CASCADE')
    op.alter_column('BloodRequest', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('BloodRequest', 'patientId',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               existing_nullable=True)
    op.alter_column('BloodRequest', 'hospitalId',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               existing_nullable=True)
    op.alter_column('BloodRequest', 'urgency',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('BloodRequest', 'city',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('BloodRequest', 'notes',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index('BloodRequest_status_city_bloodGroup_idx', table_name='BloodRequest')
    op.drop_constraint('BloodRequest_hospitalId_fkey', 'BloodRequest', type_='foreignkey')
    op.drop_constraint('BloodRequest_patientId_fkey', 'BloodRequest', type_='foreignkey')
    op.create_foreign_key(None, 'BloodRequest', 'Patient', ['patientId'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'BloodRequest', 'Hospital', ['hospitalId'], ['id'], ondelete='SET NULL')
    op.alter_column('Donation', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('Donation', 'donorId',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('Donation', 'bloodBankId',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               existing_nullable=True)
    op.alter_column('Donation', 'hospitalId',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               existing_nullable=True)
    op.alter_column('Donation', 'donationDate',
               existing_type=postgresql.TIMESTAMP(precision=3),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('Donation', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.drop_constraint('Donation_hospitalId_fkey', 'Donation', type_='foreignkey')
    op.drop_constraint('Donation_donorId_fkey', 'Donation', type_='foreignkey')
    op.drop_constraint('Donation_bloodBankId_fkey', 'Donation', type_='foreignkey')
    op.create_foreign_key(None, 'Donation', 'Donor', ['donorId'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'Donation', 'BloodBank', ['bloodBankId'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'Donation', 'Hospital', ['hospitalId'], ['id'], ondelete='SET NULL')
    op.alter_column('Donor', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('Donor', 'userId',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('Donor', 'city',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('Donor', 'address',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.drop_index('Donor_bloodGroup_city_availabilityStatus_idx', table_name='Donor')
    op.drop_index('Donor_userId_key', table_name='Donor')
    op.create_unique_constraint(None, 'Donor', ['userId'])
    op.alter_column('EmergencyRequest', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('EmergencyRequest', 'requesterId',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('EmergencyRequest', 'hospitalId',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               existing_nullable=True)
    op.alter_column('EmergencyRequest', 'city',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('EmergencyRequest', 'urgency',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.create_index(op.f('ix_EmergencyRequest_requesterId'), 'EmergencyRequest', ['requesterId'], unique=False)
    op.drop_constraint('EmergencyRequest_hospitalId_fkey', 'EmergencyRequest', type_='foreignkey')
    op.drop_constraint('EmergencyRequest_requesterId_fkey', 'EmergencyRequest', type_='foreignkey')
    op.create_foreign_key(None, 'EmergencyRequest', 'Hospital', ['hospitalId'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'EmergencyRequest', 'Patient', ['requesterId'], ['id'], ondelete='RESTRICT')
    op.alter_column('Hospital', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('Hospital', 'userId',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('Hospital', 'hospitalName',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               existing_nullable=False)
    op.alter_column('Hospital', 'registrationNumber',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('Hospital', 'city',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('Hospital', 'address',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.drop_index('Hospital_registrationNumber_key', table_name='Hospital')
    op.drop_index('Hospital_userId_key', table_name='Hospital')
    op.create_unique_constraint(None, 'Hospital', ['registrationNumber'])
    op.create_unique_constraint(None, 'Hospital', ['userId'])
    op.alter_column('Notification', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('Notification', 'userId',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('Notification', 'title',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('Notification', 'type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('Notification', 'createdAt',
               existing_type=postgresql.TIMESTAMP(precision=3),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index(op.f('ix_Notification_userId'), 'Notification', ['userId'], unique=False)
    op.drop_constraint('Notification_userId_fkey', 'Notification', type_='foreignkey')
    op.create_foreign_key(None, 'Notification', 'User', ['userId'], ['id'], ondelete='CASCADE')
    op.alter_column('Patient', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('Patient', 'userId',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('Patient', 'city',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('Patient', 'address',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.drop_index('Patient_userId_key', table_name='Patient')
    op.create_unique_constraint(None, 'Patient', ['userId'])
    op.alter_column('User', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('User', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('User', 'email',
               existing_type=sa.TEXT(),
               type_=sa.String(length=254),
               existing_nullable=False)
    op.alter_column('User', 'phone',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('User', 'passwordHash',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('User', 'createdAt',
               existing_type=postgresql.TIMESTAMP(precision=3),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('User', 'updatedAt',
               existing_type=postgresql.TIMESTAMP(precision=3),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.drop_index('User_email_key', table_name='User')
    op.create_index(op.f('ix_User_email'), 'User', ['email'], unique=True)
    op.create_index(op.f('ix_User_role'), 'User', ['role'], unique=False)
    op.create_index(op.f('ix_User_status'), 'User', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_User_status'), table_name='User')
    op.drop_index(op.f('ix_User_role'), table_name='User')
    op.drop_index(op.f('ix_User_email'), table_name='User')
    op.create_index('User_email_key', 'User', ['email'], unique=True)
    op.alter_column('User', 'updatedAt',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(precision=3),
               existing_nullable=False)
    op.alter_column('User', 'createdAt',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(precision=3),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('User', 'passwordHash',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('User', 'phone',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('User', 'email',
               existing_type=sa.String(length=254),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('User', 'name',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('User', 'id',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'Patient', type_='unique')
    op.create_index('Patient_userId_key', 'Patient', ['userId'], unique=True)
    op.alter_column('Patient', 'address',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('Patient', 'city',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('Patient', 'userId',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('Patient', 'id',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'Notification', type_='foreignkey')
    op.create_foreign_key('Notification_userId_fkey', 'Notification', 'User', ['userId'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_index(op.f('ix_Notification_userId'), table_name='Notification')
    op.alter_column('Notification', 'createdAt',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(precision=3),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('Notification', 'type',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('Notification', 'title',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('Notification', 'userId',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('Notification', 'id',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'Hospital', type_='unique')
    op.drop_constraint(None, 'Hospital', type_='unique')
    op.create_index('Hospital_userId_key', 'Hospital', ['userId'], unique=True)
    op.create_index('Hospital_registrationNumber_key', 'Hospital', ['registrationNumber'], unique=True)
    op.alter_column('Hospital', 'address',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('Hospital', 'city',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('Hospital', 'registrationNumber',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('Hospital', 'hospitalName',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('Hospital', 'userId',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('Hospital', 'id',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'EmergencyRequest', type_='foreignkey')
    op.drop_constraint(None, 'EmergencyRequest', type_='foreignkey')
    op.create_foreign_key('EmergencyRequest_requesterId_fkey', 'EmergencyRequest', 'Patient', ['requesterId'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.create_foreign_key('EmergencyRequest_hospitalId_fkey', 'EmergencyRequest', 'Hospital', ['hospitalId'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.drop_index(op.f('ix_EmergencyRequest_requesterId'), table_name='EmergencyRequest')
    op.alter_column('EmergencyRequest', 'urgency',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('EmergencyRequest', 'city',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('EmergencyRequest', 'hospitalId',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('EmergencyRequest', 'requesterId',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('EmergencyRequest', 'id',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'Donor', type_='unique')
    op.create_index('Donor_userId_key', 'Donor', ['userId'], unique=True)
    op.create_index('Donor_bloodGroup_city_availabilityStatus_idx', 'Donor', ['bloodGroup', 'city', 'availabilityStatus'], unique=False)
    op.alter_column('Donor', 'address',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('Donor', 'city',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('Donor', 'userId',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('Donor', 'id',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'Donation', type_='foreignkey')
    op.drop_constraint(None, 'Donation', type_='foreignkey')
    op.drop_constraint(None, 'Donation', type_='foreignkey')
    op.create_foreign_key('Donation_bloodBankId_fkey', 'Donation', 'BloodBank', ['bloodBankId'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.create_foreign_key('Donation_donorId_fkey', 'Donation', 'Donor', ['donorId'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.create_foreign_key('Donation_hospitalId_fkey', 'Donation', 'Hospital', ['hospitalId'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.alter_column('Donation', 'status',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('Donation', 'donationDate',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(precision=3),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('Donation', 'hospitalId',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('Donation', 'bloodBankId',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('Donation', 'donorId',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('Donation', 'id',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'BloodRequest', type_='foreignkey')
    op.drop_constraint(None, 'BloodRequest', type_='foreignkey')
    op.create_foreign_key('BloodRequest_patientId_fkey', 'BloodRequest', 'Patient', ['patientId'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.create_foreign_key('BloodRequest_hospitalId_fkey', 'BloodRequest', 'Hospital', ['hospitalId'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.create_index('BloodRequest_status_city_bloodGroup_idx', 'BloodRequest', ['status', 'city', 'bloodGroup'], unique=False)
    op.alter_column('BloodRequest', 'notes',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('BloodRequest', 'city',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('BloodRequest', 'urgency',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('BloodRequest', 'hospitalId',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('BloodRequest', 'patientId',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('BloodRequest', 'id',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'BloodInventory', type_='foreignkey')
    op.create_foreign_key('BloodInventory_bloodBankId_fkey', 'BloodInventory', 'BloodBank', ['bloodBankId'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_index(op.f('ix_BloodInventory_bloodBankId'), table_name='BloodInventory')
    op.create_index('BloodInventory_bloodBankId_bloodGroup_idx', 'BloodInventory', ['bloodBankId', 'bloodGroup'], unique=False)
    op.alter_column('BloodInventory', 'updatedAt',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(precision=3),
               existing_nullable=False)
    op.alter_column('BloodInventory', 'bloodBankId',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('BloodInventory', 'id',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'BloodBank', type_='unique')
    op.drop_constraint(None, 'BloodBank', type_='unique')
    op.create_index('BloodBank_userId_key', 'BloodBank', ['userId'], unique=True)
    op.create_index('BloodBank_registrationNumber_key', 'BloodBank', ['registrationNumber'], unique=True)
    op.alter_column('BloodBank', 'address',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('BloodBank', 'city',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('BloodBank', 'registrationNumber',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('BloodBank', 'name',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('BloodBank', 'userId',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('BloodBank', 'id',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'AuditLog', type_='foreignkey')
    op.create_foreign_key('AuditLog_userId_fkey', 'AuditLog', 'User', ['userId'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.drop_index(op.f('ix_AuditLog_userId'), table_name='AuditLog')
    op.create_index('AuditLog_action_createdAt_idx', 'AuditLog', ['action', 'createdAt'], unique=False)
    op.alter_column('AuditLog', 'createdAt',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(precision=3),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('AuditLog', 'metadata',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('AuditLog', 'entityId',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('AuditLog', 'entity',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               nullable=False)
    op.alter_column('AuditLog', 'action',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('AuditLog', 'userId',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('AuditLog', 'id',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.create_table('_prisma_migrations',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('checksum', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('finished_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('migration_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('logs', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('rolled_back_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('applied_steps_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='_prisma_migrations_pkey')
    )
    # ### end Alembic commands ###
